### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by jungyeup** [KU-CVLAB/Talk3D#4]
(talk3d) F:\Talk3D>sh do_preprocess.sh
mkdir: cannot create directory 'F:\\Talk3D\\videos/temporalv3': File exists
[INFO] ===== extract audio from F:\Talk3D\videos\temporalv3.mp4 to F:\Talk3D\videos/temporalv3\aud.wav =====
ffmpeg version 2023-09-07-git-9c9f48e7f2-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-dxva2 --enable-d3d11va --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58. 19.100 / 58. 19.100
  libavcodec     60. 26.100 / 60. 26.100
  libavformat    60. 11.100 / 60. 11.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'F:\Talk3D\videos\temporalv3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf60.11.100
  Duration: 00:00:05.60, start: 0.000000, bitrate: 857 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 576x1024, 719 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.26.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:1 -> #0:0 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'F:\Talk3D\videos/temporalv3\aud.wav':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    ISFT            : Lavf60.11.100
  Stream #0:0(und): Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, stereo, s16, 512 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc60.26.100 pcm_s16le
[out#0/wav @ 000001ccd7399680] video:0kB audio:348kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.021870%
size=     348kB time=00:00:05.57 bitrate= 512.2kbits/s speed= 548x
[INFO] ===== extracted audio =====
[INFO] ===== extract audio labels for F:\Talk3D\videos/temporalv3\aud.wav =====
[WARN] audio has 2 channels, only use the first.
[INFO] loaded audio stream F:\Talk3D\videos/temporalv3\aud.wav: (89165,)
[INFO] loading ASR model cpierse/wav2vec2-large-xlsr-53-esperanto...
C:\Users\User\.conda\envs\talk3d\lib\site-packages\transformers\configuration_utils.py:363: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(
[START]
 oregandani mi idaj erbon orio tugie
[END]
[INFO] save all feats for training purpose...
[INFO] saved logits to F:\Talk3D\videos/temporalv3\aud_eo.npy
[INFO] ===== extracted audio labels =====
Traceback (most recent call last):
  File "./preprocess_utils/vive3d_cropping.py", line 19, in <module>
    from vive3D.visualizer import *
ModuleNotFoundError: No module named 'vive3D'
Traceback (most recent call last):
  File "./preprocess_utils/detect_wav2lip_bbox.py", line 42, in <module>
    main()
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "./preprocess_utils/detect_wav2lip_bbox.py", line 21, in main
    _main(**config)
  File "./preprocess_utils/detect_wav2lip_bbox.py", line 31, in _main
    fa = face_detection.FaceAlignment(face_detection.LandmarksType._2D, flip_input=False)
  File "F:\Talk3D\./Wav2Lip\face_detection\api.py", line 62, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose)
  File "F:\Talk3D\./Wav2Lip\face_detection\detection\sfd\sfd_detector.py", line 24, in __init__
    model_weights = torch.load(path_to_detector)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 958, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
preprocess_utils/do_au_detection.sh: line 11: docker: command not found
mv: cannot stat 'F:\Talk3D\videos/temporalv3/data_openface/au.csv': No such file or directory
Usage: personalize_generator.py [OPTIONS]
Try 'personalize_generator.py --help' for help.

Error: No such option: --directory_name
Traceback (most recent call last):
  File "invert_video.py", line 99, in <module>
    main()
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\User\.conda\envs\talk3d\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "invert_video.py", line 32, in main
    _main(**config)
  File "invert_video.py", line 45, in _main
    assert os.path.exists(savepoint_path), f'Savepoint path does not exist. Run personalize_generator.py first!'
AssertionError: Savepoint path does not exist. Run personalize_generator.py first!
cp: cannot stat 'savepoints/temporalv3_trial/G_tune.pkl': No such file or directory
cp: cannot stat 'savepoints/temporalv3_trial/inversion_0-0_angles.pt': No such file or directory
cp: cannot stat 'savepoints/temporalv3_trial/inversion_w_person.pt': No such file or directory

(talk3d) F:\Talk3D>

**Comment by mlnyang** [comment]
It appears that the "vive3d" module is not being imported in the "./preprocess_utils/vive3d_cropping.py" file, because the path is incorrectly specified.
Please try to edit line14-17 in "./preprocess_utils/vive3d_cropping.py" file which is:
```
PATH = os.path.realpath(__file__)
folders = PATH.split(os.path.sep)
new_path = os.path.join('/', *folders[:-2])
sys.path.append(new_path)
```
to:
```
PATH = os.path.realpath(__file__)
new_path = os.path.dirname(os.path.dirname(PATH))
sys.path.append(new_path)
```
