### ISSUE TITLE
ERROR: Exception:

### ISSUE THREAD

**Issue by jungyeup** [KU-CVLAB/Talk3D#8]
ERROR: Exception:
Traceback (most recent call last):
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000

**Comment by jungyeup** [comment]
(talk3d) ***@***.***:~/Talk3D$ sh demo.sh
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.1'
@@@@@@@@@@@@@@@@@@@@@
@  Training Talk3D  @
@@@@@@@@@@@@@@@@@@@@@
N_gpus: 1
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.1'
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    spawn_mp(_main, world_size)
  File "main.py", line 39, in spawn_mp
    mp.spawn(running_fn,args=(world_size,),nprocs=world_size,join=True)
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py",
line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon,
start_method='spawn')
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py",
line 198, in start_processes
    while not context.join():
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py",
line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py",
line 69, in _wrap
    fn(i, *args)
  File "/home/Ubuntu/Talk3D/main.py", line 29, in _main
    setup(rank, world_size,opts)
  File "/home/Ubuntu/Talk3D/main.py", line 35, in setup
    distributed.init_process_group('nccl', rank=rank, world_size=world_size)
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py",
line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File
"/home/Ubuntu/anaconda3/envs/talk3d/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py",
line 738, in _new_process_group_helper
    pg = ProcessGroupNCCL(prefix_store, rank, world_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

리눅스에서 돌리는데 이렇게 에러떠요

torch==1.12.1+cu116 설치돼있어요


2024년 4월 24일 (수) 오후 6:09, Jaehoon Ko ***@***.***>님이 작성:

**Comment by jungyeup** [comment]
혹시 윈도우에서도 돌아가나요?


2024년 4월 25일 (목) 오전 6:01, 심정엽 ***@***.***>님이 작성:

**Comment by mlnyang** [comment]
I guess the errors still occur from CUDA environment settings, especially on Windows, as the code hasn't been tested on that platform. We only tested in Ubuntu 18.04, 20.04. 

We'll further explain in Korean if you leave an email via `kjh9604@korea.ac.kr`.
